// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Constants
{
        public const string achievement_its_a_new_day = "CgkI99TKipAJEAIQAg"; // <GPGSID>
        public const string achievement_my_fingers_dont_even_hurt = "CgkI99TKipAJEAIQAw"; // <GPGSID>
        public const string achievement_its_a_new_dawn = "CgkI99TKipAJEAIQAQ"; // <GPGSID>
        public const string leaderboard_highest_people_per_second = "CgkI99TKipAJEAIQBg"; // <GPGSID>
        public const string package_name = "com.TapInvasion"; // <GPGSID>
        public const string achievement_its_over_9000 = "CgkI99TKipAJEAIQBA"; // <GPGSID>
        public const string achievement_what_its_over_thats_all = "CgkI99TKipAJEAIQBQ"; // <GPGSID>

}

